--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/FrozenArea/RedSkyBlockX
build-by-default: true
branches:
- master
projects:
  RedSkyBlockX:
    path: ""
    libs:
      - src: CortexPE/Commando/Commando
        version: 3.1.0
      - src: Muqsit/SimplePacketHandler/SimplePacketHandler
        version: 0.1.3
      - src: Muqsit/InvMenu/InvMenu
        version: 4.6.1
      - src: NhanAZ/libBedrock/libBedrock
        version: 1.0.0
...
