--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/RedCraftGH/RedSkyBlock
branches:
- master
projects:
  RedSkyBlock:
    path: ""
    libs:
      - src: CortexPE/Commando/Commando
        version: ^3.1.0
      - src: Muqsit/SimplePacketHandler/SimplePacketHandler
        version: ^0.1.0
...
