name: RedSkyBlock
author: RedCraftPE
version: 0.0.1-BETA
api: 4.0.0
main: RedCraftPE\RedSkyBlock\SkyBlock
permissions:
  redskyblock.admin:
    default: op
    description: With this permission players will recieve access to all RedSkyBlock Admin commands.
  redskyblock.bypass:
    default: op
    description: With this permission players can bypass SkyBlock boundaries.
  redskyblock.createworld:
    default: false
    description: With this permission players can create a world ready for SkyBlock!
  redskyblock.setworld:
    default: false
    description: With this permission players can select the world used for SkyBlock.
  redskyblock.reload:
    default: false
    description: With this permission players can reload the SkyBlock files.
  redskyblock.zone:
    default: false
    description: With this permission players can manage the custom island zone.
  redskyblock.island:
    default: true
    description: With this permission players will have access to the basic SkyBlock commands.
  redskyblock.members:
    default: false
    description: With this permission players can have unlimited members on their SkyBlock island.
  redskyblock.fly:
    default: false
    description: With this permission players can fly in the SkyBlock world.
