name: RedSkyBlockX
author: [RedCraftPE, NhanAZ]
version: 6.0.0-ALPHA
api: 4.0.0
main: RedCraftPE\RedSkyBlockX\SkyBlock
permissions:
  redskyblockx.admin:
    default: op
    description: With this permission players will recieve access to all RedSkyBlockX Admin commands.
  redskyblockx.bypass:
    default: op
    description: With this permission players can bypass SkyBlock boundaries.
  redskyblockx.createworld:
    default: false
    description: With this permission players can create a world ready for SkyBlock!
  redskyblockx.setworld:
    default: false
    description: With this permission players can select the world used for SkyBlock.
  redskyblockx.reload:
    default: false
    description: With this permission players can reload the SkyBlock files.
  redskyblockx.zone:
    default: false
    description: With this permission players can manage the custom island zone.
  redskyblockx.island:
    default: true
    description: With this permission players will have access to the basic SkyBlock commands.
  redskyblockx.members:
    default: false
    description: With this permission players can have unlimited members on their SkyBlock island.
  redskyblockx.fly:
    default: false
    description: With this permission players can fly in the SkyBlock world.
