---
# IN ORDER FOR MANUAL CHANGES IN THIS FILE TO TAKE PLACE THE COMMAND /is reload MUST BE USED ON THE SERVER OR THE SERVER MUST BE RESTARTED

# Format: "block_name: %chance" %chance MUST ADD UP TO 100
Generator Ores:
  cobblestone: 60
  coal_ore: 8
  lapis_ore: 8
  redstone_ore: 8
  iron_ore: 7
  gold_ore: 4
  diamond_ore: 3
  emerald_ore: 2

# Format: "item_name: count"
Starting Items:
  ice: 2
  lava_bucket: 1
  string: 12
  bone_meal: 2
  sugar_cane: 1
  pumpkin_seeds: 1
  cactus: 1
  melon: 1
  dirt: 1
  red_mushroom: 1

# Format: "block_name: value"
Valuable Blocks:
  emerald_block: 15
  diamond_block: 10
  gold_block: 5
  iron_block: 5
  redstone_block: 3
  lapis_lazuli_block: 3
  coal_block: 1

Island Interval: 600
Island Size: 100
Island Max Size: 300
Island Spawn Y: 26

Island Hunger: true #Turn off if you do not want players to lose hunger in the SkyBlock world.
Fall Damage: true #Turn off if you do not want fall damage in the SkyBlock world.

Keep Inventory: false #Turn on if you do not want players to lose their inventory upon death.

Island Boundaries: false #Invisible barrier that forces players to stay within island boundaries -- stability untested : working on possible optimizations?

Reset Cooldown: 86400 #The time in seconds a player must wait before being able to restart their SkyBlock island again. 86400 seconds is one day.

Autosave Timer: 5 # Every x minutes all islands will autosave. Default: 5 minutes. Server restart required for changes to take effect.

Member Limit: 3

Create Teleport: true
